Feature Engineering / 특성공

In [1]:
import pandas as pd
import numpy as np
# 가상의 쇼핑몰 고객 데이터 테이블 생성
data = {
    'CustomerID': [101, 102, 103, 104, 105],
    'JoinDate': ['2025-01-15 14:30:00', '2025-03-22 09:15:00', '2025-06-01 18:45:00', '2025-06-07 11:00:00', '2026-02-14 23:10:00'],
    'Age': [19, 45, 28, 37, 62],
    'AnnualIncome': [15000, 300000, 48000, 72000, 450000],  # 연간 소득 (소수의 초고소득자 존재)
    'PurchaseCount': [15, 2, 8, 12, 1],                  # 구매 횟수
    'AvgOrderValue': [25000, 500000, 40000, 60000, 1500000] # 평균 구매 금액
}
df = pd.DataFrame(data)
df

,CustomerID,JoinDate,Age,AnnualIncome,PurchaseCount,AvgOrderValue
0,101,2025-01-15 14:30:00,19,15000,15,25000
1,102,2025-03-22 09:15:00,45,300000,2,500000
2,103,2025-06-01 18:45:00,28,48000,8,40000
3,104,2025-06-07 11:00:00,37,72000,12,60000
4,105,2026-02-14 23:10:00,62,450000,1,1500000

In [2]:
df['JoinDate'] = pd.to_datetime(df["JoinDate"])

df

,CustomerID,JoinDate,Age,AnnualIncome,PurchaseCount,AvgOrderValue
0,101,2025-01-15 14:30:00,19,15000,15,25000
1,102,2025-03-22 09:15:00,45,300000,2,500000
2,103,2025-06-01 18:45:00,28,48000,8,40000
3,104,2025-06-07 11:00:00,37,72000,12,60000
4,105,2026-02-14 23:10:00,62,450000,1,1500000

In [14]:
df

,CustomerID,JoinDate,Age,AnnualIncome,PurchaseCount,AvgOrderValue,JoinYear,JoinMonth,JoinDay,JoinHour,JoinDayofWeek
0,101,2025-01-15 14:30:00,19,15000,15,25000,2025,1,15,14,Wednesday
1,102,2025-03-22 09:15:00,45,300000,2,500000,2025,3,22,9,Saturday
2,103,2025-06-01 18:45:00,28,48000,8,40000,2025,6,1,18,Sunday
3,104,2025-06-07 11:00:00,37,72000,12,60000,2025,6,7,11,Saturday
4,105,2026-02-14 23:10:00,62,450000,1,1500000,2026,2,14,23,Saturday

In [13]:
# 정보 추출
df["JoinYear"]= df["JoinDate"].dt.year
df["JoinMonth"]= df["JoinDate"].dt.month
df["JoinDay"]= df["JoinDate"].dt.day
df["JoinHour"]= df["JoinDate"].dt.hour
df["JoinDayofWeek"]= df["JoinDate"].dt.day_name()

In [16]:
import numpy as np

In [19]:
# 소득 데이터를 로그 변환
df["Income_Log"] = np.log1p(df["AnnualIncome"])

In [20]:
print(df["AnnualIncome"].values)
print(df["Income_Log"].values)

[ 15000 300000  48000  72000 450000]
[ 9.61587214 12.61154109 10.77897712 11.18443529 13.01700508]

In [21]:
# 구간 설정
bins = [0, 19, 39, 59, 100]
label = ["Youth", "YoungAdult", "MiddleAge", "Senir"]

df["AgeGroup"] = pd.cut(df["Age"], bins=bins, labels=label)

In [22]:
df

,CustomerID,JoinDate,Age,AnnualIncome,PurchaseCount,AvgOrderValue,JoinYear,JoinMonth,JoinDay,JoinHour,JoinDayofWeek,Income_Log,AgeGroup
0,101,2025-01-15 14:30:00,19,15000,15,25000,2025,1,15,14,Wednesday,9.615872,Youth
1,102,2025-03-22 09:15:00,45,300000,2,500000,2025,3,22,9,Saturday,12.611541,MiddleAge
2,103,2025-06-01 18:45:00,28,48000,8,40000,2025,6,1,18,Sunday,10.778977,YoungAdult
3,104,2025-06-07 11:00:00,37,72000,12,60000,2025,6,7,11,Saturday,11.184435,YoungAdult
4,105,2026-02-14 23:10:00,62,450000,1,1500000,2026,2,14,23,Saturday,13.017005,Senir

In [24]:
# 총 소비금액 (구매 쵯수 * 평균 구매 금액)
df["totalSpand"] = df["PurchaseCount"] * df["AvgOrderValue"]

In [25]:
df

,CustomerID,JoinDate,Age,AnnualIncome,PurchaseCount,AvgOrderValue,JoinYear,JoinMonth,JoinDay,JoinHour,JoinDayofWeek,Income_Log,AgeGroup,totalSpand
0,101,2025-01-15 14:30:00,19,15000,15,25000,2025,1,15,14,Wednesday,9.615872,Youth,375000
1,102,2025-03-22 09:15:00,45,300000,2,500000,2025,3,22,9,Saturday,12.611541,MiddleAge,1000000
2,103,2025-06-01 18:45:00,28,48000,8,40000,2025,6,1,18,Sunday,10.778977,YoungAdult,320000
3,104,2025-06-07 11:00:00,37,72000,12,60000,2025,6,7,11,Saturday,11.184435,YoungAdult,720000
4,105,2026-02-14 23:10:00,62,450000,1,1500000,2026,2,14,23,Saturday,13.017005,Senir,1500000