전처리

In [1]:
import pandas as pd

In [ ]:
# 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', None],
    'Age': [25, None, 30],
    'Score': [85, 90, None]
}

df=pd.DataFrame(data)

In [4]:
df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2    NaN  30.0    NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      float64
 2   Score   2 non-null      float64
dtypes: float64(2), str(1)
memory usage: 204.0 bytes

In [7]:
df.isnull().sum()       # 데이터가 많고 결측치도 많다면 한 눈에 보기 어려우니 sum 사용

Name     1
Age      1
Score    1
dtype: int64

In [ ]:
# 결측치 데이터 삭제
df_missing_row = df.dropna()

print(df_missing_row)

    Name   Age  Score
0  Alice  25.0   85.0

In [14]:
df_missing_cols = df.dropna(axis=1)           # 삭제된 열 개수

print(df_missing_cols)
df_missing_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2]

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [ ]:
# 결측치에 특정 값으도 대체
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Socre"] = df["score"].fillna(df["Socre"].median())
df["Name"] = df["Name"].fillna(df["Name"].mod(0))

In [2]:
# 이상치 처리 -> 삭제, 치환
# 이상치 범워
data = {
    "score" : [70, 75, 80, 85, 90, 500]
}

df = pd.DataFrame(data)
df

   score
0     70
1     75
2     80
3     85
4     90
5    500

In [3]:
Q1 = df["score"].quantile(0.25)
Q3 = df["score"].quantile(0.75)

IQR = Q3 - Q1

print(Q1, Q3, IQR)

76.25 88.75 12.5

In [4]:
low_ = Q1 - 1.5 * IQR
up_ = Q3 + 1.5 * IQR

print(low_, up_)

57.5 107.5

In [7]:
result_df = df[(df["score"] < low_) | (df["score"] > up_)]

result_df

   score
5    500

In [8]:
result_df1 = df[(df["score"] >= low_) | (df["score"] <= up_)]

result_df1

   score
0     70
1     75
2     80
3     85
4     90
5    500

In [11]:
# 이상치 데이터의 변경
df["score"] = df["score"].astype(float)          # astype() : 특정 타입으로 변경
df.loc[df["score"] < low_ , "score"] = low_
df.loc[df["score"] > up_, "score"] = up_

In [12]:
import pandas as pd
# 예제 데이터
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'Score': [85, 90, 85, 95, 90]
}
df = pd.DataFrame(data)
print('원본 데이터프레임:')
print(df)

원본 데이터프레임:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [18]:
print(df.duplicated())
print(df.duplicated().sum())
print(df.duplicated(subset=["Name"]))
print(df.duplicated(subset=["Name"]).sum())
print(df[df.duplicated()])

0    False
1    False
2     True
3    False
4     True
dtype: bool
2
0    False
1    False
2     True
3    False
4     True
dtype: bool
2
    Name  Age  Score
2  Alice   25     85
4    Bob   30     90

In [20]:
# 중복된 행 삭제
df_cleared = df.drop_duplicates()
df_cleared

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95

In [ ]:
df_cleared1 = df.drop_duplicates(keep="last")
df_cleared1

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [22]:
df_cleared2 = df.drop_duplicates(keep=False)
df_cleared2

      Name  Age  Score
3  Charlie   35     95

In [23]:
df_cleared3 = df.drop_duplicates(keep="last", subset=["Name"])
df_cleared3

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90