Pandas

In [1]:
import pandas as pd

In [3]:
# DataFrame : 2차원 형식(행과 열)의 표 모양으로 데이터 구조 생성

data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30, 25]
}

df = pd.DataFrame(data)

In [5]:
print(df)
print(type(df))

   name  age
0  cool   20
1   hot   30
2  king   25
<class 'pandas.DataFrame'>

In [ ]:
df.head(1)      # 기본 5개

   name  age
0  cool   20

In [ ]:
df.tail()       # 기본 5개

   name  age
0  cool   20
1   hot   30
2  king   25

In [11]:
df.shape

(3, 2)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [13]:
# 기초 통계

df.describe()

        age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [15]:
print(df['age'].sum())
print(df['age'].mean())

75
25.0

In [18]:
data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30, 25],
    'score' : [90, 70, 60]
}

df = pd.DataFrame(data)

In [19]:
df

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   25     60

In [21]:
# 표 -> 원하는 표
df1 = df[['name', 'score']]

In [22]:
df1

   name  score
0  cool     90
1   hot     70
2  king     60

In [24]:
df1['passed'] = df1['score'] >= 70

In [25]:
df1

   name  score  passed
0  cool     90    True
1   hot     70    True
2  king     60   False

In [27]:
df1[['name', 'passed']]

   name  passed
0  cool    True
1   hot    True
2  king   False

In [32]:
df1.loc[2, 'score'] = 80

In [41]:
df1

   name  score  passed
0  cool     90    True
1   hot     70    True
2  king     80   False

In [43]:
df1['passed'] = df1['score'] >= 70

In [44]:
df1

   name  score  passed
0  cool     90    True
1   hot     70    True
2  king     80    True

In [77]:
df1.loc[1, 'score'] = None

In [78]:
df1

   name  score  passed
0  cool   90.0    True
1   hot    NaN    True
2  king   80.0    True

In [79]:
# 결측치 찾기

df1.isnull()

    name  score  passed
0  False  False   False
1  False   True   False
2  False  False   False

In [80]:
# 결측치에만 특정 값 저장

df1['score'] = df1['score'].fillna(100)

In [81]:
df1

   name  score  passed
0  cool   90.0    True
1   hot  100.0    True
2  king   80.0    True

In [82]:
df1.to_csv('output.csv', index=False)

In [83]:
data_csv = pd.read_csv('output.csv')

In [84]:
data_csv

   name  score  passed
0  cool   90.0    True
1   hot  100.0    True
2  king   80.0    True